### ISSUE TITLE
Order of execution of logical view joins

### ISSUE THREAD

**Issue by elsdvlee** [kg-construct/rml-lv#37]
If there is more than one join, what is the order of execution? (Remark of @pmaria moved from spec to issues)

**Comment by elsdvlee** [comment]
The logical view joins are more limited than SQL joins. The join conditions are linked to one join and only involve an equal condition on references from the child logical view and compared to references from the parent logical view. Moreover only left (outer) joins and inner joins are defined. Therefore I think that (associative) order doesn't matter.
@pmaria @tirrolo Can you contribute to the solution for this issue?

**Comment by tirrolo** [comment]
Ciao,

joins are associative, so that order of execution should not affect the final result.

I'd like here to stay as consistent as possible with RML-Core and R2RML. For R2RML, in particular, no order of execution is specified. This because, in that setting, the order in which joins in a SQL query are executed are decided by the database system according to its internal cost model.

I'd like to leave the same flexibility here as well.

**Comment by elsdvlee** [comment]
@pmaria Do you agree to close this issue, not specifying the order of the joins?

**Comment by pmaria** [comment]
Agreed
